services:
  - type: web
    name: pos-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && ./node_modules/.bin/nest build
    startCommand: node dist/main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
